services:
  javascript:
    image: node:18
    container_name: js_app
    volumes:
      - ./outputs:/outputs
      - ./app/javascript:/app
    working_dir: /app
    command: sh -c "node main.js > /outputs/javascript_output.txt"

  python:
    image: python:3.11
    container_name: python_app
    volumes:
      - ./outputs:/outputs
      - ./app/python:/app
    working_dir: /app
    command: ["sh", "-c", "python main.py > /outputs/python_output.txt"]

  ruby:
    image: ruby:3.2
    container_name: ruby_app
    volumes:
      - ./outputs:/outputs
      - ./app/ruby:/app
    working_dir: /app
    command: ["sh", "-c", "ruby main.rb > /outputs/ruby_output.txt"]

  c:
    image: gcc:latest
    container_name: c_app
    volumes:
      - ./outputs:/outputs
      - ./app/c:/app
    working_dir: /app
    command: ["/bin/sh", "-c", "gcc main.c -o main && ./main > /outputs/c_output.txt"]
    
  rust:
    image: rust:latest
    container_name: rust_app
    volumes:
      - ./outputs:/outputs
      - ./app/rust:/app
    working_dir: /app
    command: ["sh", "-c", "cargo run --release > /outputs/rust_output.txt"]




